// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets survey from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');
var mongoose = require('mongoose');
var Joi = require('joi');
var User = require('../users/user-dao');
var Schema = mongoose.Schema;

var surveySchema = mongoose.Schema({

  survey_id: Schema.Types.ObjectId,
  title: String,
  title_i8ln: {},

  description: String,
  description_i8ln: {},

  type: String,
  creator: Schema.Types.ObjectId,
  organization_id: Schema.Types.ObjectId,

  state: String,

  published_on: Date,
  published_ts: Number,

  sector: String,

  questions: [Schema.Types.ObjectId],

  live: Boolean,

  live_details: [{
    start: Date,
    start_ts: Number,
    end: Date,
    end_ts: Number
  }],

  // Versioning
  version: Number,
  version_comment: String,
  head: Boolean,

  journal: [{
    remote_ip: String,
    user_agent: String,
    client_id: String,
    user_id: Schema.Types.ObjectId,
    modified_time: Date,
    modified_time_ts: Number,
    changelog: [{}]
  }],

  last_modified: Date,
  last_modified_ts: Number

});
var surveySchema = mongoose.Schema({}, {strict: false});

// Survey Instance methods
surveySchema.methods.magic = function(callback){
  return this.model('Survey').find({}, callback)
}


// Survey Collection methods
surveySchema.statics.magic = function (callback) {
  return this.find({ name: new RegExp(name, 'i') }, callback);
}

// Survey Collection method to embed
surveySchema.statics.embed = function (callback) {
  return this.find({ name: new RegExp(name, 'i') }, callback);
}

// Survey Collection method to get mappings of models according to ObjectId fields
surveySchema.statics.getObjectIDModel = function () {
  var hash = {
    'questions': 'Question',
    'organisation_id': null,
    'creator': null,
    'user_id': 'User',
  }

  return hash;
}


// Survey Indexes

// by organisation_id survey id and 
surveySchema.index({
  organisation_id: 1,
  survey_id: 1,
  version: 1,
})



var Survey = mongoose.model('Survey', surveySchema);

module.exports = Survey
