// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets Answer from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');
var mongoose = require('mongoose');
var Joi = require('joi');
var Schema = mongoose.Schema;

var answerSchema = mongoose.Schema({

  survey_id: Schema.Types.ObjectId,
  survey_version: Number,  
  survey_version_id: Schema.Types.ObjectId,

  question_id: Schema.Types.ObjectId,
  question_version: Number,
  question_version_id: Schema.Types.ObjectId,

  organization_id: Schema.Types.ObjectId,

  text: String,
  url: String,
  location: {
  	type: String,
  	coordinates: [Schema.Types.Mixed]
  },
  option_ids: [String],
  type: Array,

  child_question: Boolean,
  context: Schema.Types.Mixed,

  timestamp: Date,
  timestamp_ts: Number,
  linked_response_id: Schema.Types.ObjectId,
  linked_response_version: Number

});



// Answer Instance methods

// Answer Collection methods

// Answer Indexes

// by organisation_id Answer id and 
answerSchema.index({
  organisation_id: 1,
  survey_id: 1,
  question_id: 1,  
  survey_version: 1,
  question_version: 1,
  location: 1,
  linked_response_id: 1
});



var Answer = mongoose.model('Answer', answerSchema);

module.exports = Answer