// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets user from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');
var mongoose = require('mongoose');
var Joi = require('joi');
var Schema = mongoose.Schema;

var userSchema = mongoose.Schema({
	name: String,
	email: String
});

// user Instance methods
userSchema.methods.magic = function(callback){
  return this.model('User').find({}, callback)
}


// user Collection methods
userSchema.statics.magic = function (callback) {
  return this.find({ name: new RegExp(name, 'i') }, cb);
}

// user Indexes


var user = mongoose.model('User', userSchema);
user['userSchema'] = userSchema;

module.exports = user