// This is a file generated by the yeoman generator hapijs

/**
 * All the endpoints for anything related to question
 *
 * @type {exports}
 */
var Joi = require('joi');
var questionController = require('./question-ctrl');
var routeValidation = require('./question-route-validation')

module.exports = function() {
  return [
    {
      method: 'POST',
      path: '/questions',
      config: {
        tags: ['api'],
        description: 'Creates a question',
        handler: questionController.create,
        // validate: routeValidation.post
      }
    },

    {
      method: 'POST',
      path: '/questions/bulkCreate',
      config: {
        tags: ['api'],
        description: 'Creates multiple questions. To be used only for uploading data when necessary or Dummy Data',
        handler: questionController.bulkCreate,
        // validate: routeValidation.post
      }
    },
		
    {
      method: 'GET',
      path: '/questions',
      config : {
        tags: ['api'],
        description: 'Fetches all questions',
        handler: questionController.find
      }
    },
    {
      method: 'GET',
      path: '/questions/findOne',
      config : {
        tags: ['api'],
        description: 'Fetches one question',
        handler: questionController.findOne
      }
    },
    {
      method: 'GET',
      path: '/questions/count',
      config : {
        tags: ['api'],
        description: 'Returns number of questions based on any or no conditions',
        handler: questionController.count
      }
    },

    {
      method: 'GET',
      path: '/questions/distinct',
      config : {
        tags: ['api'],
        description: 'Finds distinct values of field for documents matching conditions',
        handler: questionController.distinct
      }
    },
		
    {
      method: 'GET',
      path: '/questions/{id}',
      config : {
        tags: ['api'],        
        description: 'Fetches a question by id',
        handler: questionController.findById,
        // validate: routeValidation.getById
      }
    },
		
    {
      method: 'PUT',
      path: '/questions/{id}',
      config : {
        tags: ['api'],
        description: 'Updates a question for a specific id',
        handler: questionController.update,
        // validate: routeValidation.put
      }
    },
		
    {
      method: 'DELETE',
      path: '/questions/{id}',
      config : {
        tags: ['api'],
        description: 'Remove a question for a specific id',
        handler: questionController.remove,
        // validate: routeValidation.delete
      }
    }
		
		/* Add new methods above */
  ]
}();
